export default {
  name: 'post',
  type: 'document',
  title: 'Post',
  fields: [
    { name: 'title', title: 'Title', type: 'string' },
    { name: 'slug', title: 'Slug', type: 'slug', options: { source: 'title', maxLength: 96 } },
    { name: 'body', title: 'Body', type: 'blockContent' },
    {
      name: 'mainImage',
      title: 'Main Image',
      type: 'image',
      options: {
        hotspot: true,
      },
    },
    { name: 'imageAlt', title: 'Image Alt Text', type: 'string' },
    { name: 'publishedAt', title: 'Published At', type: 'datetime' },
    { name: 'category', title: 'Category', type: 'reference', to: { type: 'category' } },
    { name: 'difficultyLevel', title: 'Difficulty Level', type: 'string' },
    { name: 'toolsNeeded', title: 'Tools Needed', type: 'array', of: [{ type: 'string' }] },
    { name: 'materialsNeeded', title: 'Materials Needed', type: 'array', of: [{ type: 'string' }] },
    { name: 'stepByStepInstructions', title: 'Step-by-Step Instructions', type: 'array', of: [{ type: 'string' }] },
    { name: 'safetyTips', title: 'Safety Tips', type: 'array', of: [{ type: 'string' }] },
    { name: 'commonMistakes', title: 'Common Mistakes', type: 'array', of: [{ type: 'string' }] },
    { name: 'estimatedTime', title: 'Estimated Time', type: 'string' },
    { name: 'estimatedCost', title: 'Estimated Cost', type: 'string' },
    { name: 'seoTitle', title: 'SEO Title', type: 'string' },
    { name: 'seoDescription', title: 'SEO Description', type: 'text' },
    { name: 'authorAIName', title: 'Author AI Name', type: 'string' },
    { name: 'commentsEnabled', title: 'Comments Enabled', type: 'boolean' },
    { name: 'updateLog', title: 'Update Log', type: 'array', of: [{ type: 'string' }] },
    { name: 'readTime', title: 'Read Time (minutes)', type: 'string' },
    { name: 'featured', title: 'Featured Post', type: 'boolean' },
    { name: 'videoURL', title: 'Video URL', type: 'url' },
    { name: 'projectTags', title: 'Project Tags', type: 'array', of: [{ type: 'string' }] },
    { name: 'faq', title: 'FAQ', type: 'array', of: [{ type: 'string' }] },
    { name: 'affiliateLinks', title: 'Affiliate Links', type: 'array', of: [{ type: 'string' }] },
    { name: 'internalLink', title: 'Internal Link Reference', type: 'string' },
    { name: 'externalSourceURL', title: 'External Source URL', type: 'url' },
    { name: 'isTestPost', title: 'Is Test Post?', type: 'boolean' },
    { name: 'pinnedCategorySortOrder', title: 'Pinned Sort Order', type: 'number' },
    { name: 'schemaTypeVersion', title: 'Schema Type Version', type: 'string' }
  ]
}
